name: Docker Compose Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  depoy:
    if: github.event.created == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ArwynFr/actions-docker-context@v2
        with:
          docker_host: ${{ secrets.DOCKER_HOST }}
          context_name: remote
          use_context: true
          ssh_cert: ${{ secrets.SSH_CERT }}
          ssh_key: ${{ secrets.SSH_KEY }}

      - name: Docker Compose Up
        run: docker compose up --build -d
